### PR TITLE
Gantry Tilt Correction.

### PR DESCRIPTION
**Pull request by muschellij2**
I see `options.isTiltCorrect = false`, which is crucial for CT scans with gantry tilt.  

I have added this option to `readDicom`, but this is problematic as the rows of `scanDicom` no longer match one-to-one when tilt is present.  I am trying to figure out how to adapt this using `scanDicom` and any help is appreciated.

### CODE REVIEW

**Comment by jonclayden** [comment]
Thanks for flagging this up. I was planning to expose this and other options ahead of the next release, which is fairly imminent, so this is a good time to get this resolved.

Since you have experience with this option, can you briefly outline its effect? I don't work with CT data so I'm not familiar with the issue. If there's any suitable public test data around that would be great to know about, too...

**Comment by jonclayden** [comment]
Also, is there any disadvantage to just fixing this option to true? From a quick look, that seems to be the effect of the upstream code.

**Comment by muschellij2** [comment]
I don't think so necessarily.  The only thing I've also added is to put
that information into the description and data.frame, which may be wanted.
The overall disadvantages of having data like this as well as images where
slice thickness varies (again CT), is that 2 scans will be output from
dcm2niix rather than 1 so the binding of the rows of scanDicom and the
niftis from readDicom will no longer be valid.

John

**Comment by jonclayden** [comment]
Right, I see: `dcm2niix` outputs both a tilt-corrected image and an uncorrected image, which means that more images are returned than are expected. The easiest solution would be to only return the corrected image, so I'll figure out the cleanest way to implement that. As for the extra option to `readDicom`, if there's no reason not to correct then I don't think it's needed.

**Comment by muschellij2** [comment]
Agreed.

John

**Comment by jonclayden** [comment]
Great -- hopefully the last couple of commits should address the issue then. Let me know if there is still a problem. Thanks again for your contribution!

**Pull request closed without merging**
